In [1]:
import pandas as pd

# Load the Excel file to examine its structure
file_path = 'C:/Users/ASUS/Desktop/Msc Course/CT calibration/Dataset/SNR_CNR/Khana.xlsx'
data = pd.read_excel(file_path)

# Display the first few rows of the dataframe to understand its structure
data.head(20)

,SNR first row,second row,3 row,4 row,5 row,6 row,7 row,Unnamed: 7,CNR first row,second row.1,3 row.1,4 row.1,5 row.1,6 row.1,7 row.1
0,-29.682509,-27.150087,-38.106607,-26.144064,-34.922259,-17.746944,-24.106756,NaN,-904.610523,-940.812686,-923.702283,-867.907368,-855.142415,-894.936406,-813.852302
1,-17.936779,-19.285361,-14.465669,-17.223911,-19.397933,-13.932888,-15.359088,NaN,-904.338263,-920.258953,-902.268577,-825.113236,-815.455653,-797.370492,-820.564279
2,-11.926642,-10.469931,-12.596353,-9.382199,-10.312785,-9.174388,-8.902049,NaN,-880.051247,-845.755861,-839.134991,-736.882586,-749.079907,-767.702556,-716.865003
3,-10.325543,-7.099796,-8.027561,-7.636739,-6.701242,-7.62813,-6.199237,NaN,-857.739924,-799.473822,-775.731856,-634.378898,-654.452311,-707.224211,-609.470932
4,-7.686171,-6.083682,-4.432851,-5.967751,-6.013603,-3.478614,-4.144916,NaN,-821.789219,-742.36145,-665.82443,-551.288824,-589.866649,-534.554565,-555.027106
5,-6.027200,-6.192753,-5.444544,-5.417310,-3.984677,-2.671721,-5.616433,NaN,-789.738863,-712.709489,-657.421272,-512.576187,-567.798868,-430.166325,-545.529399
6,-5.074648,-5.755620,-4.494774,-4.018290,-3.23076,-2.478544,-2.780274,NaN,-770.468575,-687.884874,-504.809386,-483.893363,-477.437948,-474.371752,-438.007943
7,-7.502915,-4.576813,-4.479903,-3.523739,-4.763493,-1.783992,-4.910263,NaN,-814.658553,-558.112425,-528.477518,-393.36958,-503.941197,-473.254357,-426.388492
8,-3.906916,-5.661937,-4.743099,-5.213711,-2.343014,-2.625692,-4.832578,NaN,-690.17672,-696.705389,-446.958902,-572.721961,-325.565031,-221.628056,-516.995628
9,-3.817190,-3.115959,-5.027283,-2.506952,-5.059365,-4.318525,-2.716598,NaN,-721.536345,-430.346675,-551.39032,-225.417422,-379.005838,-186.397331,-473.647363
10,-4.888241,0.314949,-4.012097,3.678767,-2.676538,-4.726879,1.344651,NaN,-610.695591,25.126382,-270.251363,164.503985,-162.910128,-610.497345,28.318589
11,-6.321586,-2.149699,-2.332817,-2.876916,8.751389,1.701599,-2.881928,NaN,-773.203082,-308.259013,-135.881958,-278.806506,225.930515,55.214294,-50.152486
12,-5.590558,-1.403043,-1.193065,1.039760,5.909175,5.091101,8.192991,NaN,-737.561361,-179.657381,-48.848867,69.018976,242.087782,249.231771,231.636644
13,-4.616192,-4.695016,-6.21416,-4.661839,-7.381315,-4.482018,-5.37531,NaN,-698.082765,-746.678052,-770.100437,-582.994785,-594.792936,-583.153461,-582.942897
14,-5.085714,-6.166660,-3.996396,-5.957850,-5.675157,-4.37977,-4.746866,NaN,-771.53901,-784.222903,-673.376057,-617.318299,-560.970253,-565.152484,-526.04771
15,-4.942260,-3.802124,-5.939495,-3.652244,-5.167557,-3.816962,-3.658685,NaN,-736.906324,-503.398017,-603.894578,-390.577832,-558.196552,-374.052963,-343.551203
16,-7.624482,-5.128918,-5.735053,-5.390221,-3.845017,-5.08747,-4.240396,NaN,-818.533955,-747.332515,-625.485004,-517.179141,-402.702899,-507.725825,-399.100162
17,-7.357211,-3.003695,-3.234062,-3.759668,-3.584745,-2.494519,-3.201388,NaN,-820.320346,-374.985484,-539.491902,-333.598428,-353.659757,-184.659005,-141.295524
18,-4.023715,-5.980723,-4.433817,-3.419071,-3.774653,-3.895559,-3.481531,NaN,-445.945957,-687.624763,-592.303504,-187.073288,-206.894978,-81.806800,-106.729075
19,-3.185223,-2.373962,6.565214,0.648697,-2.833404,0.852865,-2.125464,NaN,-456.117959,-272.99473,95.036644,33.852003,-162.014236,30.504990,-1.298654

In [2]:
import pandas as pd
import os
# Correct path to the file
file_path = 'C:/Users/ASUS/Desktop/Msc Course/CT calibration/Dataset/SNR_CNR/Khana.xlsx'

# Load the Excel file with all sheets
data = pd.read_excel(file_path, sheet_name=None)

# Dictionary to hold data for all sheets processed
processed_data_corrected = {}

# Process each sheet similarly
for sheet_name, sheet_data in data.items():
    # Initialize lists to store the resulting data
    img_nums = []
    stack_nos = []
    snr_values = []
    cnr_values = []

    # Iterate through each block of 13 rows and each of the 7 columns for SNR and CNR
    for block in range(25):  # 25 images
        for col in range(7):  # 7 columns for SNR (columns 0 to 6)
            for row in range(13):  # 13 values per image
                img_nums.append(block + 1)  # Image number
                stack_nos.append(f"Stack{col * 13 + row + 1}")  # Stack number, reset each image
                if (block * 13 + row) < len(sheet_data):
                    snr_index = col  # SNR values from the first 7 columns
                    cnr_index = col + 8  # CNR values from columns I to O (index 8 to 14)
                    snr_values.append(sheet_data.iloc[block * 13 + row, snr_index])  # SNR value
                    cnr_values.append(sheet_data.iloc[block * 13 + row, cnr_index])  # CNR value
                else:
                    snr_values.append(None)  # Append None if out of bounds
                    cnr_values.append(None)

    # Create a new DataFrame with the structured data
    processed_sheet = pd.DataFrame({
        "ImgNum": img_nums,
        "StackNo": stack_nos,
        "SNR": snr_values,
        "CNR": cnr_values
    })

    # Add to the dictionary of processed data
    processed_data_corrected[sheet_name] = processed_sheet

# Save the new DataFrame to a new Excel file with sheet names retained
file_path = 'C:/Users/ASUS/Desktop/Msc Course/CT calibration/Dataset/SNR_CNR/Khana_processed.xlsx'

# Check if the file exists
if not os.path.exists(file_path):
    # Create a new empty DataFrame
    df = pd.DataFrame()
    
    # Save the empty DataFrame to the specified path
    df.to_excel(file_path, index=False)
    print(f"File created at {file_path}")
else:
    print(f"File already exists at {file_path}")
output_path_all_sheets_corrected = 'C:/Users/ASUS/Desktop/Msc Course/CT calibration/Dataset/SNR_CNR/Khana_processed.xlsx'
with pd.ExcelWriter(output_path_all_sheets_corrected, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:  # Open in append mode using openpyxl
    for sheet_name, sheet_data in processed_data_corrected.items():
        sheet_data.to_excel(writer, sheet_name=sheet_name, index=False)

print("Data processed and appended to:", output_path_all_sheets_corrected)

File created at C:/Users/ASUS/Desktop/Msc Course/CT calibration/Dataset/SNR_CNR/Khana_processed.xlsx
Data processed and appended to: C:/Users/ASUS/Desktop/Msc Course/CT calibration/Dataset/SNR_CNR/Khana_processed.xlsx